# Generated by Django 4.2.10 on 2024-02-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_account_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='priority_level',
            field=models.IntegerField(choices=[(0, 'No Priority'), (1, 'Low Priority'), (2, 'Medium Priority'), (3, 'High Priority')], default=0),
        ),
    ]
