# Generated by Django 4.2.10 on 2024-03-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_todotask_is_done"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todotask",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", to="core.todotag"
            ),
        ),
    ]
