# Generated by Django 4.2.10 on 2024-03-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_todotask_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="gender",
            field=models.CharField(
                choices=[("M", "MALE"), ("F", "FEMALE"), ("O", "OTHER")],
                default="O",
                max_length=1,
            ),
        ),
    ]
