# Generated by Django 4.2.10 on 2024-03-02 18:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_account_q2"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="q3",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(
                    choices=[
                        (0, 0),
                        (1, 1),
                        (2, 2),
                        (3, 3),
                        (4, 4),
                        (5, 5),
                        (6, 6),
                        (7, 7),
                        (8, 8),
                        (9, 9),
                        (10, 10),
                        (11, 11),
                        (12, 12),
                        (13, 13),
                        (14, 14),
                        (15, 15),
                        (16, 16),
                        (17, 17),
                        (18, 18),
                        (19, 19),
                    ]
                ),
                default=list,
                size=None,
            ),
        ),
    ]
