# Generated by Django 4.2.10 on 2024-03-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_event_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="title",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
    ]
