# Generated by Django 4.2.10 on 2024-03-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_notification_datetime_todotask_notification_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todotask',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='todotask',
            name='user',
        ),
        migrations.DeleteModel(
            name='ToDoTag',
        ),
        migrations.DeleteModel(
            name='ToDoTask',
        ),
    ]
