# Generated by Django 4.2.10 on 2024-03-10 16:28

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SpacedLearningTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("subject", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_done", models.BooleanField(default=False)),
                ("is_finished", models.BooleanField(default=False)),
                (
                    "new_material",
                    models.IntegerField(
                        choices=[
                            (0, "Nothing was new"),
                            (1, "Almost nothing new"),
                            (2, "Something was new"),
                            (3, "Fifty/fifty new topic"),
                            (4, "Mainly new topic"),
                            (5, "Completely new topic"),
                        ],
                        default=5,
                    ),
                ),
                (
                    "pages_cnt",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(30),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                (
                    "minutes_per_day",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(2000),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                (
                    "next_train_date",
                    models.DateField(
                        default=datetime.date(2024, 3, 10), editable=False
                    ),
                ),
                (
                    "progress_grade",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(2),
                            django.core.validators.MinValueValidator(0),
                        ],
                    ),
                ),
                ("delta_days_daily", models.IntegerField(default=0)),
                ("delta_days_const", models.IntegerField(default=10)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spacedlearningtasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
