# Generated by Django 4.2.10 on 2024-03-10 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spacedlearning", "0002_spacedlearningtask_rate_spacedlearningtask_weight"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="spacedlearningtask",
            name="progress_grade",
        ),
    ]
