# Generated by Django 4.2.10 on 2024-03-10 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spacedlearning", "0003_remove_spacedlearningtask_progress_grade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="spacedlearningtask",
            name="is_done",
        ),
    ]
